include				setup.mk


# ***************************** CONFIGURATION ******************************** #

NAME			:=	libftpp.a
MSG_PROGRESS	:=	"📦"
COLOR_MAKE		=	$(STY_WHI)

include				$(MAKEFILES_DIR)/config.mk
include				$(MAKEFILES_DIR)/build.mk
include				$(MAKEFILES_DIR)/doc.mk
include				$(MAKEFILES_DIR)/help.mk
