name: Pull Request Labeler

on:
  pull_request_target:
    types: [opened]

jobs:
  labeler:
    name: Labeler
    permissions:
      contents: read
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: actions/labeler@v6
        with:
          configuration-path: .github/labeler.yaml
